### ISSUE TITLE
naotu.baidu.com/为什么还不支持 HTTPS?

### ISSUE THREAD

**Issue by zhuangyin8** [fex-team/kityminder-editor#511]
naotu.baidu.com/:1 Mixed Content: The page at 'https://naotu.baidu.com/' was loaded over HTTPS, but requested an insecure script 'http://naotu.baidu.com/public/dist/kityminder.online.min.js?_=2dbf34d4d0334cf8'. This request has been blocked; the content must be served over HTTPS.
naotu.baidu.com/:16 Uncaught ReferenceError: $ is not defined
    at naotu.baidu.com/:16
naotu.baidu.com/:261 Mixed Content: The page at 'https://naotu.baidu.com/' was loaded over HTTPS, but requested an insecure script 'http://hm.baidu.com/hm.js?0703917f224067c887f3664479a03887'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ naotu.baidu.com/:261
naotu.baidu.com/:1 Mixed Content: The page at 'https://naotu.baidu.com/' was loaded over HTTPS, but requested an insecure image 'http://naotu.baidu.com/public/images/indexbackground.jpg'. This content should also be served over HTTPS.
/C:/Users/zhuan/AppData/Local/Google/Chrome%20SxS/User%20Data/Default/Extensions/gppongmhjkpfnbhagpmjfkannfbllamg/5.1.1_0/js/content.js:10 Uncaught ReferenceError: browser is not defined
    at /C:/Users/zhuan/AppData/Local/Google/Chrome%20SxS/User%20Data/Default/Extensions/gppongmhjkpfnbhagpmjfkannfbllamg/5.1.1_0/js/content.js:10
naotu.baidu.com/:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'value' of null
    at h (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/simSearch.js:3:928)
    at i (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/simSearch.js:3:1132)
    at Object.e [as simSearch_isAuthenticated] (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/simSearch.js:3:467)
    at c (chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/js/common/Browser.js:3:3911)

**Comment by techird** [comment]
HTTPS 强需求

**Comment by WinstonH** [comment]
是的，美中不足就是没有https了。作为主打云端的产品，https很有必要

**Comment by im0qianqian** [comment]
建议支持，另外也建议增加一个新功能：嵌入到其他站点
